### ISSUE TITLE
Cake4: Support

### ISSUE THREAD

**Issue by dereuromark** [php-http/cakephp-adapter#10]
I have started the branch for Cake4 beta:

https://github.com/php-http/cakephp-adapter/compare/master...dereuromark:master

Are you able to make a `cake4` branch here for now?
So I can remove the overhead in config?
```json
    "require": {
        ...
        "php-http/cakephp-adapter": "dev-master as 0.2.0"
    },
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:dereuromark/cakephp-adapter.git"
        }
    ],
```
Thank you :)

**Comment by dereuromark** [comment]
ping @Nyholm etc

**Comment by sagikazarmark** [comment]
@dereuromark would you be open to stepping up as a maintainer for this package? I can add you to the repo if you are.

**Comment by dereuromark** [comment]
Sure, I can definitely help out here.

**Comment by sagikazarmark** [comment]
Great! I added you to the repo, so you should be able to create that branch.

**Comment by dereuromark** [comment]
Cool. I let you know once you can review.

**Comment by dereuromark** [comment]
https://github.com/php-http/cakephp-adapter/pull/11 can now be reviewed.
