### ISSUE TITLE
Missing for stable release

### ISSUE THREAD

**Issue by joelwurtz** [php-http/cakephp-adapter#3]
- [ ] Documentation

Anything else ?

**Comment by Nyholm** [comment]
From Slack about Buzz and React: 

> @nyholm: I know Im conservative to tag 1.0, and I also know that there are plenty of major version numbers after 1.0. But what is our general rule? I feel that Buzz is too immature. React is mature but it has only 500 downloads and unstable dependencies.
> 
> Guzzle5 on the other hand has been used quite a lot and no PR has been merged the last couple of months. Thats when I think we should tag 1.0. Any thoughts on this topic? (edited)
> 
> @dbu: in my opinion, we should tag 1.0 when we either are confident or when nothing much happened for a month and the library looks ok
> 
> eternal beta is also not great - people will still start to rely on it and doing a BC break from some beta to the actual 1.0 will be more trouble than just bumping to 2.0
> 
> unstable dependencies is not great however. is there any chance they become stable?
> 
> @nyholm: Not in the case of react as far as I know
> 
> Lets tag 1.0 for Buzz at the end of August.
> 
> As for React I’ll leave that up to someone else. It has been no/few changes there but I do not know if that is because none uses it or because it is perfect.

For the cackephp-adapter I think we should wait 3-6 months before a stable release. Just to see how people are using it and if they are happy with it.

**Comment by dereuromark** [comment]
Given how rare this is used, we can probably close this for now and keep using 0.x majors.
